// Mocks generated by Mockito 5.4.6 from annotations
// in navtool/test/core/services/background_task_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:navtool/core/error/app_error.dart' as _i13;
import 'package:navtool/core/logging/app_logger.dart' as _i12;
import 'package:navtool/core/models/gps_position.dart' as _i11;
import 'package:navtool/core/models/gps_signal_quality.dart' as _i3;
import 'package:navtool/core/models/position_history.dart' as _i4;
import 'package:navtool/core/services/download_service.dart' as _i2;
import 'package:navtool/core/services/gps_service.dart' as _i10;
import 'package:navtool/core/state/download_state.dart' as _i9;
import 'package:workmanager/src/options.dart' as _i7;
import 'package:workmanager/src/workmanager.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBatchDownloadProgress_0 extends _i1.SmartFake
    implements _i2.BatchDownloadProgress {
  _FakeBatchDownloadProgress_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGpsSignalQuality_1 extends _i1.SmartFake
    implements _i3.GpsSignalQuality {
  _FakeGpsSignalQuality_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePositionHistory_2 extends _i1.SmartFake
    implements _i4.PositionHistory {
  _FakePositionHistory_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAccuracyStatistics_3 extends _i1.SmartFake
    implements _i4.AccuracyStatistics {
  _FakeAccuracyStatistics_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovementState_4 extends _i1.SmartFake implements _i4.MovementState {
  _FakeMovementState_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePositionFreshness_5 extends _i1.SmartFake
    implements _i4.PositionFreshness {
  _FakePositionFreshness_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Workmanager].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkmanager extends _i1.Mock implements _i5.Workmanager {
  MockWorkmanager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void executeTask(_i5.BackgroundTaskHandler? backgroundTask) =>
      super.noSuchMethod(
        Invocation.method(#executeTask, [backgroundTask]),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> initialize(
    Function? callbackDispatcher, {
    bool? isInDebugMode = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #initialize,
              [callbackDispatcher],
              {#isInDebugMode: isInDebugMode},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> registerOneOffTask(
    String? uniqueName,
    String? taskName, {
    String? tag,
    _i7.ExistingWorkPolicy? existingWorkPolicy,
    Duration? initialDelay = Duration.zero,
    _i7.Constraints? constraints,
    _i7.BackoffPolicy? backoffPolicy,
    Duration? backoffPolicyDelay = Duration.zero,
    _i7.OutOfQuotaPolicy? outOfQuotaPolicy,
    Map<String, dynamic>? inputData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #registerOneOffTask,
              [uniqueName, taskName],
              {
                #tag: tag,
                #existingWorkPolicy: existingWorkPolicy,
                #initialDelay: initialDelay,
                #constraints: constraints,
                #backoffPolicy: backoffPolicy,
                #backoffPolicyDelay: backoffPolicyDelay,
                #outOfQuotaPolicy: outOfQuotaPolicy,
                #inputData: inputData,
              },
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> registerPeriodicTask(
    String? uniqueName,
    String? taskName, {
    Duration? frequency,
    String? tag,
    _i7.ExistingWorkPolicy? existingWorkPolicy,
    Duration? initialDelay = Duration.zero,
    _i7.Constraints? constraints,
    _i7.BackoffPolicy? backoffPolicy,
    Duration? backoffPolicyDelay = Duration.zero,
    _i7.OutOfQuotaPolicy? outOfQuotaPolicy,
    Map<String, dynamic>? inputData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #registerPeriodicTask,
              [uniqueName, taskName],
              {
                #frequency: frequency,
                #tag: tag,
                #existingWorkPolicy: existingWorkPolicy,
                #initialDelay: initialDelay,
                #constraints: constraints,
                #backoffPolicy: backoffPolicy,
                #backoffPolicyDelay: backoffPolicyDelay,
                #outOfQuotaPolicy: outOfQuotaPolicy,
                #inputData: inputData,
              },
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancelByUniqueName(String? uniqueName) =>
      (super.noSuchMethod(
            Invocation.method(#cancelByUniqueName, [uniqueName]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancelByTag(String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#cancelByTag, [tag]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancelAll() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAll, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [DownloadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadService extends _i1.Mock implements _i2.DownloadService {
  MockDownloadService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> downloadChart(
    String? chartId,
    String? url, {
    String? expectedChecksum,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadChart,
              [chartId, url],
              {#expectedChecksum: expectedChecksum},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> pauseDownload(String? chartId) =>
      (super.noSuchMethod(
            Invocation.method(#pauseDownload, [chartId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> resumeDownload(String? chartId, {String? url}) =>
      (super.noSuchMethod(
            Invocation.method(#resumeDownload, [chartId], {#url: url}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancelDownload(String? chartId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelDownload, [chartId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<String>> getDownloadQueue() =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadQueue, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Stream<double> getDownloadProgress(String? chartId) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadProgress, [chartId]),
            returnValue: _i6.Stream<double>.empty(),
          )
          as _i6.Stream<double>);

  @override
  _i6.Future<void> addToQueue(
    String? chartId,
    String? url, {
    _i2.DownloadPriority? priority = _i2.DownloadPriority.normal,
    String? expectedChecksum,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addToQueue,
              [chartId, url],
              {#priority: priority, #expectedChecksum: expectedChecksum},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeFromQueue(String? chartId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromQueue, [chartId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearQueue() =>
      (super.noSuchMethod(
            Invocation.method(#clearQueue, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.QueueItem>> getDetailedQueue() =>
      (super.noSuchMethod(
            Invocation.method(#getDetailedQueue, []),
            returnValue: _i6.Future<List<_i2.QueueItem>>.value(
              <_i2.QueueItem>[],
            ),
          )
          as _i6.Future<List<_i2.QueueItem>>);

  @override
  _i6.Future<String> startBatchDownload(
    List<String>? chartIds,
    List<String>? urls, {
    _i2.DownloadPriority? priority = _i2.DownloadPriority.normal,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #startBatchDownload,
              [chartIds, urls],
              {#priority: priority},
            ),
            returnValue: _i6.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(
                  #startBatchDownload,
                  [chartIds, urls],
                  {#priority: priority},
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<_i2.BatchDownloadProgress> getBatchProgress(String? batchId) =>
      (super.noSuchMethod(
            Invocation.method(#getBatchProgress, [batchId]),
            returnValue: _i6.Future<_i2.BatchDownloadProgress>.value(
              _FakeBatchDownloadProgress_0(
                this,
                Invocation.method(#getBatchProgress, [batchId]),
              ),
            ),
          )
          as _i6.Future<_i2.BatchDownloadProgress>);

  @override
  _i6.Stream<_i2.BatchDownloadProgress> getBatchProgressStream(
    String? batchId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBatchProgressStream, [batchId]),
            returnValue: _i6.Stream<_i2.BatchDownloadProgress>.empty(),
          )
          as _i6.Stream<_i2.BatchDownloadProgress>);

  @override
  _i6.Future<void> pauseBatchDownload(String? batchId) =>
      (super.noSuchMethod(
            Invocation.method(#pauseBatchDownload, [batchId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> resumeBatchDownload(String? batchId) =>
      (super.noSuchMethod(
            Invocation.method(#resumeBatchDownload, [batchId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancelBatchDownload(String? batchId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelBatchDownload, [batchId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i9.DownloadProgress>> getPersistedDownloadState() =>
      (super.noSuchMethod(
            Invocation.method(#getPersistedDownloadState, []),
            returnValue: _i6.Future<List<_i9.DownloadProgress>>.value(
              <_i9.DownloadProgress>[],
            ),
          )
          as _i6.Future<List<_i9.DownloadProgress>>);

  @override
  _i6.Future<void> recoverDownloads(
    List<_i9.DownloadProgress>? persistedDownloads,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#recoverDownloads, [persistedDownloads]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> enableBackgroundNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#enableBackgroundNotifications, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.DownloadNotification>> getPendingNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingNotifications, []),
            returnValue: _i6.Future<List<_i2.DownloadNotification>>.value(
              <_i2.DownloadNotification>[],
            ),
          )
          as _i6.Future<List<_i2.DownloadNotification>>);

  @override
  _i6.Future<int> getMaxConcurrentDownloads() =>
      (super.noSuchMethod(
            Invocation.method(#getMaxConcurrentDownloads, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> setMaxConcurrentDownloads(int? maxConcurrent) =>
      (super.noSuchMethod(
            Invocation.method(#setMaxConcurrentDownloads, [maxConcurrent]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.ResumeData?> getResumeData(String? chartId) =>
      (super.noSuchMethod(
            Invocation.method(#getResumeData, [chartId]),
            returnValue: _i6.Future<_i2.ResumeData?>.value(),
          )
          as _i6.Future<_i2.ResumeData?>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GpsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGpsService extends _i1.Mock implements _i10.GpsService {
  MockGpsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> startLocationTracking() =>
      (super.noSuchMethod(
            Invocation.method(#startLocationTracking, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> stopLocationTracking() =>
      (super.noSuchMethod(
            Invocation.method(#stopLocationTracking, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i11.GpsPosition?> getCurrentPosition() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPosition, []),
            returnValue: _i6.Future<_i11.GpsPosition?>.value(),
          )
          as _i6.Future<_i11.GpsPosition?>);

  @override
  _i6.Future<_i11.GpsPosition?> getCurrentPositionWithFallback() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPositionWithFallback, []),
            returnValue: _i6.Future<_i11.GpsPosition?>.value(),
          )
          as _i6.Future<_i11.GpsPosition?>);

  @override
  _i6.Stream<_i11.GpsPosition> getLocationStream() =>
      (super.noSuchMethod(
            Invocation.method(#getLocationStream, []),
            returnValue: _i6.Stream<_i11.GpsPosition>.empty(),
          )
          as _i6.Stream<_i11.GpsPosition>);

  @override
  _i6.Future<bool> requestLocationPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestLocationPermission, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> checkLocationPermission() =>
      (super.noSuchMethod(
            Invocation.method(#checkLocationPermission, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> isLocationEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isLocationEnabled, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i3.GpsSignalQuality> assessSignalQuality(
    _i11.GpsPosition? position,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#assessSignalQuality, [position]),
            returnValue: _i6.Future<_i3.GpsSignalQuality>.value(
              _FakeGpsSignalQuality_1(
                this,
                Invocation.method(#assessSignalQuality, [position]),
              ),
            ),
          )
          as _i6.Future<_i3.GpsSignalQuality>);

  @override
  _i6.Future<void> logPosition(_i11.GpsPosition? position) =>
      (super.noSuchMethod(
            Invocation.method(#logPosition, [position]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.PositionHistory> getPositionHistory(Duration? timeWindow) =>
      (super.noSuchMethod(
            Invocation.method(#getPositionHistory, [timeWindow]),
            returnValue: _i6.Future<_i4.PositionHistory>.value(
              _FakePositionHistory_2(
                this,
                Invocation.method(#getPositionHistory, [timeWindow]),
              ),
            ),
          )
          as _i6.Future<_i4.PositionHistory>);

  @override
  _i6.Future<List<_i3.GpsSignalQuality>> getSignalQualityTrend(
    Duration? timeWindow,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSignalQualityTrend, [timeWindow]),
            returnValue: _i6.Future<List<_i3.GpsSignalQuality>>.value(
              <_i3.GpsSignalQuality>[],
            ),
          )
          as _i6.Future<List<_i3.GpsSignalQuality>>);

  @override
  _i6.Future<void> clearPositionHistory() =>
      (super.noSuchMethod(
            Invocation.method(#clearPositionHistory, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.AccuracyStatistics> getAccuracyStatistics(
    Duration? timeWindow,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAccuracyStatistics, [timeWindow]),
            returnValue: _i6.Future<_i4.AccuracyStatistics>.value(
              _FakeAccuracyStatistics_3(
                this,
                Invocation.method(#getAccuracyStatistics, [timeWindow]),
              ),
            ),
          )
          as _i6.Future<_i4.AccuracyStatistics>);

  @override
  _i6.Future<_i4.MovementState> getMovementState(Duration? analysisWindow) =>
      (super.noSuchMethod(
            Invocation.method(#getMovementState, [analysisWindow]),
            returnValue: _i6.Future<_i4.MovementState>.value(
              _FakeMovementState_4(
                this,
                Invocation.method(#getMovementState, [analysisWindow]),
              ),
            ),
          )
          as _i6.Future<_i4.MovementState>);

  @override
  _i6.Future<_i4.PositionFreshness> getPositionFreshness() =>
      (super.noSuchMethod(
            Invocation.method(#getPositionFreshness, []),
            returnValue: _i6.Future<_i4.PositionFreshness>.value(
              _FakePositionFreshness_5(
                this,
                Invocation.method(#getPositionFreshness, []),
              ),
            ),
          )
          as _i6.Future<_i4.PositionFreshness>);

  @override
  _i6.Future<List<_i11.GpsPosition>> filterForMarineAccuracy(
    List<_i11.GpsPosition>? positions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#filterForMarineAccuracy, [positions]),
            returnValue: _i6.Future<List<_i11.GpsPosition>>.value(
              <_i11.GpsPosition>[],
            ),
          )
          as _i6.Future<List<_i11.GpsPosition>>);

  @override
  _i6.Future<_i4.CourseOverGround?> calculateCourseOverGround(
    Duration? timeWindow,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#calculateCourseOverGround, [timeWindow]),
            returnValue: _i6.Future<_i4.CourseOverGround?>.value(),
          )
          as _i6.Future<_i4.CourseOverGround?>);

  @override
  _i6.Future<_i4.SpeedOverGround?> calculateSpeedOverGround(
    Duration? timeWindow,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#calculateSpeedOverGround, [timeWindow]),
            returnValue: _i6.Future<_i4.SpeedOverGround?>.value(),
          )
          as _i6.Future<_i4.SpeedOverGround?>);
}

/// A class which mocks [AppLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLogger extends _i1.Mock implements _i12.AppLogger {
  MockAppLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void debug(String? message, {String? context, Object? exception}) =>
      super.noSuchMethod(
        Invocation.method(
          #debug,
          [message],
          {#context: context, #exception: exception},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void info(String? message, {String? context, Object? exception}) =>
      super.noSuchMethod(
        Invocation.method(
          #info,
          [message],
          {#context: context, #exception: exception},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void warning(String? message, {String? context, Object? exception}) =>
      super.noSuchMethod(
        Invocation.method(
          #warning,
          [message],
          {#context: context, #exception: exception},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void error(String? message, {String? context, Object? exception}) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [message],
          {#context: context, #exception: exception},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void logError(_i13.AppError? error) => super.noSuchMethod(
    Invocation.method(#logError, [error]),
    returnValueForMissingStub: null,
  );
}
