cmake_minimum_required(VERSION 3.20)
include("${IDENTITY_MODULE}")
set(_archive "${CMAKE_CURRENT_BINARY_DIR}/source-identity-archive")
file(MAKE_DIRECTORY "${_archive}")
navtool_read_source_identity("${_archive}" _archive_revision _archive_dirty)
if(NOT _archive_revision STREQUAL "unknown" OR NOT _archive_dirty STREQUAL "unknown")
    message(FATAL_ERROR "An extracted source archive inherited its parent's Git identity.")
endif()
navtool_read_source_identity("${SOURCE_TREE}" _source_revision _source_dirty)
if(NOT "${_source_revision}" STREQUAL "${EXPECTED_REVISION}")
    message(FATAL_ERROR "The actual router-lib source identity was not preserved.")
endif()
