name: Binary Builds Pipeline

on:
  push:
    branches: [ main, develop, 'feature/**' ]
  pull_request:
    branches: [ main, develop ]
  # Allow manual triggering from the Actions tab
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.35.1'  # Latest stable with Dart 3.8.1+ compatibility
  CI: 'true'

jobs:
  # Linux Desktop Build
  build-linux:
    name: Build Linux Desktop
    runs-on: ubuntu-latest
    timeout-minutes: 90  # NEVER CANCEL - builds take 45-90 minutes
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install system dependencies for Linux build
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          pkg-config \
          libgtk-3-dev \
          ninja-build \
          curl \
          git \
          unzip \
          clang \
          libasound2t64 \
          libxi6 \
          libxrender1 \
          libxrandr2 \
          libxcursor1 \
          libxinerama1 \
          libxss1 \
          libgl1 \
          libglu1-mesa \
          liblzma-dev \
          libstdc++-12-dev \
          ca-certificates \
          fonts-liberation
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true
        
    - name: Verify Flutter installation
      run: |
        flutter doctor -v
        flutter --version
        
    - name: Get dependencies (NEVER CANCEL - takes 5-10 minutes)
      run: flutter pub get
      
    - name: Generate mocks (NEVER CANCEL - takes 3-5 minutes)
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
      
    - name: Run Flutter Analyze (for information only - does not block build)
      run: |
        echo "=== Running Flutter Analyze for Information ==="
        flutter analyze --fatal-infos || {
          echo "⚠️  Flutter analyze found issues, but continuing with build"
          echo "Analyze issues are informational only and do not block the build"
        }
        echo "=== Flutter Analyze Complete ==="
      continue-on-error: true
      
    - name: Build Linux Desktop (Release)
      run: |
        echo "=== Starting Linux Desktop Build ==="
        flutter build linux --release
        echo "=== Linux Desktop Build Complete ==="
        
    - name: Verify build artifacts
      run: |
        if [ -d "build/linux/x64/release/bundle" ]; then
          echo "✅ Linux build artifacts created successfully"
          ls -la build/linux/x64/release/bundle/
        else
          echo "❌ Linux build artifacts not found"
          exit 1
        fi
        
    - name: Upload Linux build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-desktop-build
        path: build/linux/x64/release/bundle/
        retention-days: 30

  # Windows Desktop Build
  build-windows:
    name: Build Windows Desktop
    runs-on: windows-latest
    timeout-minutes: 90  # NEVER CANCEL - builds take 45-90 minutes
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true
        
    - name: Verify Flutter installation
      run: |
        flutter doctor -v
        flutter --version
        
    - name: Get dependencies (NEVER CANCEL - takes 5-10 minutes)
      run: flutter pub get
      
    - name: Generate mocks (NEVER CANCEL - takes 3-5 minutes)
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
      
    - name: Run Flutter Analyze (for information only - does not block build)
      run: |
        echo "=== Running Flutter Analyze for Information ==="
        flutter analyze --fatal-infos
        if ($LASTEXITCODE -ne 0) {
          echo "⚠️  Flutter analyze found issues, but continuing with build"
          echo "Analyze issues are informational only and do not block the build"
        }
        echo "=== Flutter Analyze Complete ==="
      continue-on-error: true
      
    - name: Build Windows Desktop (Release)
      run: |
        echo "=== Starting Windows Desktop Build ==="
        flutter build windows --release
        echo "=== Windows Desktop Build Complete ==="
        
    - name: Verify build artifacts
      run: |
        if (Test-Path "build/windows/x64/runner/Release") {
          echo "✅ Windows build artifacts created successfully"
          Get-ChildItem build/windows/x64/runner/Release
        } else {
          echo "❌ Windows build artifacts not found"
          exit 1
        }
        
    - name: Upload Windows build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-desktop-build
        path: build/windows/x64/runner/Release/
        retention-days: 30

  # macOS Desktop Build
  build-macos:
    name: Build macOS Desktop
    runs-on: macos-latest
    timeout-minutes: 90  # NEVER CANCEL - builds take 45-90 minutes
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true
        
    - name: Verify Flutter installation
      run: |
        flutter doctor -v
        flutter --version
        
    - name: Get dependencies (NEVER CANCEL - takes 5-10 minutes)
      run: flutter pub get
      
    - name: Generate mocks (NEVER CANCEL - takes 3-5 minutes)
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
      
    - name: Run Flutter Analyze (for information only - does not block build)
      run: |
        echo "=== Running Flutter Analyze for Information ==="
        flutter analyze --fatal-infos || {
          echo "⚠️  Flutter analyze found issues, but continuing with build"
          echo "Analyze issues are informational only and do not block the build"
        }
        echo "=== Flutter Analyze Complete ==="
      continue-on-error: true
      
    - name: Build macOS Desktop (Release)
      run: |
        echo "=== Starting macOS Desktop Build ==="
        flutter build macos --release
        echo "=== macOS Desktop Build Complete ==="
        
    - name: Verify build artifacts
      run: |
        if [ -d "build/macos/Build/Products/Release" ]; then
          echo "✅ macOS build artifacts created successfully"
          ls -la build/macos/Build/Products/Release/
        else
          echo "❌ macOS build artifacts not found"
          exit 1
        fi
        
    - name: Upload macOS build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-desktop-build
        path: build/macos/Build/Products/Release/
        retention-days: 30

  # Build Summary
  build-summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos]
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Generate build summary
      run: |
        echo "# Binary Builds Summary" > build-summary.md
        echo "" >> build-summary.md
        echo "## Build Results" >> build-summary.md
        echo "- Linux Desktop Build: ${{ needs.build-linux.result }}" >> build-summary.md
        echo "- Windows Desktop Build: ${{ needs.build-windows.result }}" >> build-summary.md
        echo "- macOS Desktop Build: ${{ needs.build-macos.result }}" >> build-summary.md
        echo "" >> build-summary.md
        echo "## Build Artifacts" >> build-summary.md
        echo "Binary builds are available as artifacts for 30 days." >> build-summary.md
        echo "" >> build-summary.md
        echo "## Analysis Information" >> build-summary.md
        echo "Flutter analyze was run on all platforms for informational purposes." >> build-summary.md
        echo "Analysis issues do not block builds - only build failures cause CI failure." >> build-summary.md
        
    - name: Upload build summary
      uses: actions/upload-artifact@v4
      with:
        name: build-summary
        path: build-summary.md